name: ByeHacker
main: ldcr.ByeHacker.ByeHacker
version: 5
author: Ldcr
softdepend: ["AuthMe"]
depend: ["ProtocolLib", "LdcrUtils"]
permissions:
    byehacker.bypass:
        default: op
    byehacker.info:
        default: op
    byehacker.manage:
        default: op
commands:
  byehacker:
