name: ByeHacker
main: ldcr.ByeHacker.ByeHacker
version: 2.0.0
author: Ldcr
softdepend: ["AuthMe"]
depend: ["ProtocolLib"]
permissions:
    byehacker.bypass:
        default: op
    byehacker.info:
        default: op
    byehacker.manage:
        default: op
commands:
  byehacker:
